config/routes.rb
General::Application.routes.draw do

  root :to => 'start_page#index'

  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'registration' }

  

  
  resources :posts do
    resources :comments
    resources :vote, :only => [:update] do
      delete 'clear'
    end
    resources :photos
  end

  
  resources :servants
  resources :categories

end

app/models/post.rb
class Post < ActiveRecord::Base

  after_create :create_vote

  attr_accessible :text, :title, :category_ids, :image

  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  has_one :vote, :dependent => :destroy
# -----------------------------------------------
  has_many :photos, :dependent => :destroy 
# -----------------------------------------------

  belongs_to :user

  validates :title, :presence => true, :length => { :minimum => 2 }
  validates :text, :presence => true, :length => { :minimum => 2 }
  
  scope :by_category_id, lambda {|cid| joins(:categories).where(['categories.id = ?',cid])}

  mount_uploader :image, ImageUploader
  


include PgSearch
pg_search_scope :search, against: [:title, :text],
	associated_against: {user: :name, comments: [:body]}

# end of 343 DB search in testing and production

	def self.text_search(query)
	  if query.present?
	    search(query)
	  else
	    scoped
	  end
	end

    protected
    
    def create_vote
      self.vote = Vote.create(:score => 0)
    end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	load_and_authorize_resource

	before_filter :set_timezone 
	
	def set_timezone  
	 min = request.cookies['time_zone'].to_i
	 Time.zone = ActiveSupport::TimeZone[min]
	end 


	def index
		@posts = Post.order('created_at DESC').text_search(params[:query]).page(params[:page]).per(6)
		
		@posts = @posts.by_category_id(params[:cat]).page(params[:page]).per(6) if params[:cat].present?
	end
	def new
		
	end
	def create
  		
  		@post.user = current_user

  		if @post.save
  		  flash[:notice] = "Post created!"
  		  redirect_to post_path(@post.id)
  		else
  		  render 'new'
  		end
	end
	def show
		
	end
	def edit
		
	end
	def update
  		
  		if @post.update_attributes(params[:post])
  		  flash[:notice] = "Post updated"
  		  redirect_to post_path(@post.id)
  		else
  		  render 'edit'
  		end
	end
	def destroy
	  
	  @post.destroy
	  redirect_to posts_path
	end
	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error.html.erb
  <% if post.errors.any? %>
    <div id="errorExplanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

app/views/posts/_form.html.erb
<div class="control-group">
  <%= f.label :title, 'Title: ', :class => "control-label" %>
  <div class="controls">
    <div class="input-prepend">
      <%= f.text_field :title, :id => "inputTitle", :placeholder => "Title of post" %>
    </div>
  </div>
</div>
<div class="control-group">
  <%= f.label :text, 'Text of post: ', :class => "control-label" %>
  <div class="controls">
    <div class="input-prepend">
      <%= f.text_area :text, :rows => 8, :id => "text_area", :placeholder => "Text of post" %>
    </div>
  </div>
</div>

<br />
<div class="controls">
<i>(leave blank if you don't want to change it)</i><br />
  <% Category.all.each do |category| %>
    <label class="checkbox inline">
      <%= check_box_tag 'post[category_ids][]', category.id %>
      <%= category.name %>
    </label>
  <% end %>
</div>

<div id='error_for_check_box'></div>

<div class="control-group">
  <div class="controls">
    <%= f.file_field :image %>
  </div>
</div>

<div class="control-group">
   <div class="controls">
    <%= f.submit "Create", :class => 'btn btn-success'  %>
   </div>
</div>

app/views/posts/_tablenew.html.erb
<% @posts.each do |post| %>
  <div class='box_of_post'>
    <div class='id_of_post'># <%= post.id %></div>
    <div class='time_pablised'>Published at: <%= post.created_at.strftime('%e %B %Y, %H:%M') %></div>
    <div class='title_box'><h4><%= link_to post.title, post_path(post.id) %></h4></div>
    <div class='body_box'>
      <% if post.image? %>
        <%= image_tag(post.image_url(:main), :alt => "some", :id => 'main_image')  %>
      <% else %>
        <%= image_tag('avatars/default_img.png', :alt => "no_image", :class => 'main_image')  %> 
      <% end %>  
      <span>
        <%= post.text.truncate(200, :separator => ' ') %>
      </span>
    </div>
    <div class='clear'></div>

    <div class='autor'>
      <span>Опубликовал:</span>
        <% if post.user.nil? %>
            <span class='del'>Deleted</span>
        <% elsif post.user.roles.first.name == "user" %>
            <%= link_to post.user.name, servant_path(post.user.id) %>
        <% elsif post.user.roles.first.name == "admin" %>    
            <%= post.user.name %>
        <% end %>
    </div>

    <div class='tags'>
      <% post.categories.each do |cat| %>
        <i class="icon-tag"></i>
        <%= link_to cat.name, posts_path(:cat=>cat.id) %>
      <% end %>
    </div>

    <div class='clear'></div>
    <div class='controls_area'>
      <span class='count_comments'>( <%= pluralize(post.comments.count, ") comment") %></span>
      <%= link_to 'Show', post_path(post.id) , :class => 'btn btn-primary admin_area_btn'%>
      
      <% if can? :update, post %> 
        <%= link_to 'Edit', edit_post_path(post.id), :class => 'btn btn-primary admin_area_btn' %>
      <% end %>
      <% if can? :destroy, post %>  
        <%= link_to 'Destroy', post_path(post.id), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger admin_area_btn' %>
      <% end %>

      <% if post.user.nil? %>
        <div class='position_for_starz'>
          <div class="raiting_index">
            <div class="raiting_blank_index"></div>
          </div>
        </div>
      <% else %>
        <div class='position_for_starz'>
            <div class='hidden_rank_index'>
              <%= number_with_precision(post.vote.score.to_f/post.vote.count_users) %>
            </div>
            
            <div class="raiting_index">
              <div class="raiting_blank_index"></div>
              <div class="raiting_votes_index"></div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% title @post.title %>

<blockquote><h2>Edit post</h2></blockquote>

<%= form_for :post, :url => post_path(@post), :html => { :class => "form-horizontal" }, :method => :put do |f| %>
	<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

<%= link_to 'back to post', post_path(@post), :class => 'btn_back btn btn-inverse btn-large'  %> 

app/views/posts/index.html.erb
<% title "All posts" %>
<blockquote><h2>List of posts</h2></blockquote>

<%= form_tag posts_path, :method => 'get', :class => 'form-search' do %>
  <div class="input-append">
    <%= text_field_tag :query, params[:query], :class => "span2 search-query", :placeholder => "Posts only" %>
    <%= button_tag "Search", :name => nil, :class => 'btn' %>
  </div>
<% end %>


<% if can? :create, Post %>
  <%= link_to 'Create new post', new_post_path, :class => 'btn btn-large btn-primary new_post' %>  
<% end %>  

<div class='paginator'>
  <%= paginate @posts, :window => 3 %>
</div>

<% if @posts.count > 0 %>
	<div id='all_posts_box'>
	  <%= render 'tablenew' %>
	</div>
<% end %>

<div class='paginator'>
  <%= paginate @posts, :window => 3 %>
</div>

app/views/posts/index.js.erb
// $('#all_posts_box').html('<%= escape_javascript render(partial: "tablenew") %>');
// $('.paginator').html('<%= escape_javascript(paginate(@posts, :window => 3, :remote => true).to_s) %>');

app/views/posts/new.html.erb
<% title "Create" %>
<blockquote><h2>Create new post</h2></blockquote>

<%= form_for @post, :html => { :class => "form-horizontal" } do |f| %>
	<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

<%= link_to 'back to all post', posts_path, :class => 'btn_back btn btn-inverse btn-large' %> 

app/views/posts/show.html.erb
<% title @post.title %>
<div id = 'box_of_post_show'>
  <% if @post.image? %>
    <%= image_tag(@post.image_url(:thumb), :alt => "some", :id => 'main_image')  %>
  <% else %>
    <%= image_tag('avatars/no_image_yet.jpg', :alt => "no_image", :id => 'main_image')  %>
  <% end %>


<div class ='title_of_post_show'>
  <%= @post.title %>
</div>
 
<div class ='text_of_post_show'>
  <%= raw RedCloth.new( sanitize( @post.text ), [:filter_html, :filter_styles, :filter_ids] ).to_html %>
</div>

<div class='clear'></div>
<div class='autor'>
  <strong>Autor:</strong>
    <% if @post.user.nil? %>
        <span class='del'>Deleted user</span>
    <% elsif @post.user.roles.first.name == "user" %>
        <%= link_to @post.user.name, servant_path(@post.user.id) %>
    <% elsif @post.user.roles.first.name == "admin" %>    
        <%= @post.user.name %>
    <% end %>
</div>

<div class='tags'>
  <strong>Categories:</strong>
  <% @post.categories.each do |cat| %>
    <%= link_to cat.name, posts_path(:cat=>cat.id) %>
  <% end %>
</div>
<div class='clear'></div>

<span class='avatar_of_post_user'>
  <% if @post.user.nil? %>
      <%= image_tag("avatars/noneavatars.png") %>
  <% elsif @post.user.roles.first.name == "user" %>
      <%= image_tag avatar_url(@post.user) %>
  <% elsif @post.user.roles.first.name == "admin" %> 
      <%= image_tag("avatars/admin.png") %>
  <% end %>
</span>
<div class='time_pablised'>Published at: <%= @post.created_at.strftime('%e %B %Y, %H:%M') %></div>


  <div id='vote_update'>
    <%= render :partial => 'vote/update', locals: { post: @post } %>
  </div>


<hr>

<div id='all_comments'>
	<%= render @post.comments %>
</div>

<div class='clear'></div>

<% if user_signed_in?  %> 
	<%= render "comments/form" %>
<% end %>


  <div class='controls_area'>
    <%= link_to "back to all", posts_path, :class => 'btn btn-primary admin_area_btn' %> 
    <% if ( current_user && current_user.id == @post.user_id ) or ( current_user && current_user.roles.first.name == "admin") %>
    	<%= link_to 'Edit', edit_post_path, :class => 'btn btn-primary admin_area_btn' %> 
      <%= link_to 'Destroy Post', post_path(@post.id), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger admin_area_btn' %>
      <%= link_to 'Upload', post_photos_path(@post), :class => 'btn admin_area_btn' %>
    <% end %>
  </div>

</div>