config/routes.rb
General::Application.routes.draw do

  root :to => 'start_page#index'

  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'registration' }

  

  
  resources :posts do
    resources :comments
    resources :vote, :only => [:update] do
      delete 'clear'
    end
    resources :photos
  end

  
  resources :servants
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :category_ids, :name

  has_and_belongs_to_many :posts
  before_destroy {|category| category.posts.clear}
  
  validates :name, :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_filter :check_admin_area_enter!

	def index
		@categories = Category.all
	end
	def new 	
		@category = Category.new
	end
	def create
		@category = Category.new(params[:category])

		if @category.save
			redirect_to :action => :index
		else 
			render 'new'
		end	
	end
	def destroy
		@category = Category.find(params[:id])
  		@category.destroy
  		redirect_to :action => :index
	end
	def check_admin_area_enter!
		if (current_user && current_user.roles.first.name == "admin")
			
		else
			redirect_to root_path, :alert => "You don't have access to this page"
		end
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% title "All categories (only admin)" %>
<div id='sixhan'>
<div id='midls'>

<blockquote><h3>Категории<h3></blockquote>

<table class="table table-striped table-bordered">
  <tr>
    <th>Categories name</th>
    <th>Actions</th>
  </tr>
  <% @categories.each do |i| %>
    <tr>
      <td><%= i.name %></td>
      <td>
        <%= link_to 'Delete categories', { :action => :destroy, :id => i.id }, :method => :delete, :confirm => 'Are you sure?' %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "Add categories", new_category_path , :class => 'btn btn-primary btn_back' %>

</div>
</div>

app/views/categories/new.html.erb
<% title "Add category (only admin)" %>
<div id='sixhan'>
<div id='midls'>

<legend><h3>Create new category</h3></legend>

<%= form_for @category do |f| %>  

    <div class="control-group">
        <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-th-list"></i></span>
          <%= f.text_field :name, :id => "inputCategory", :placeholder => "Category", :autofocus => true %>
        </div>
      </div>
    </div>
  
    <div class="control-group">
       <div class="controls">
      <%= f.submit "Add", :class => 'btn btn-success'  %>
       </div>
    </div>

<% end %>

<%= link_to 'Back', categories_path, :class => 'btn btn-inverse btn_back' %>
</div>
</div>