config/routes.rb
General::Application.routes.draw do

  root :to => 'start_page#index'

  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'registration' }

  

  
  resources :posts do
    resources :comments
    resources :vote, :only => [:update] do
      delete 'clear'
    end
    resources :photos
  end

  
  resources :servants
  resources :categories

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new

    if user.roles.first.nil?
        can :read, Post
    #not logged
    elsif user.roles.first.name == "user"
        #loged in as user
        can :read, Post
        can :create, Post
        can :update, Post, :user_id => user.id
        can :destroy, Post , :user_id => user.id 

        can :create, Comment

        can :update, Vote do |vote|
            !vote.users.include?(user)   
        # он может делать update для Vote - голоcовать ( если еще не голосовал )
        end

    elsif user.roles.first.name == "admin"
        # login as admin
        can :manage, Post # Поставил пост а не :all если будет :all то сможет голосовать вечно

        can :clear, Vote 
        can :update, Vote do |vote|
            !vote.users.include?(user)   
        end
    end

  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :category_ids, :name

  has_and_belongs_to_many :posts
  before_destroy {|category| category.posts.clear}
  
  validates :name, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	before_validation :check_for_spaces
  attr_accessible :body
  belongs_to :post
  belongs_to :user


  validates :body, :presence => true, :length => { :minimum =>  2 }


  def check_for_spaces
  	self.body = self.body.strip
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :users
  has_many :states
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photo_file, :post_id
  belongs_to :post

  # mount_uploader :photo_file, PhotoFileUploader

 	mount_uploader :photo_file, PhotoFileUploader


end

app/models/post.rb
class Post < ActiveRecord::Base

  after_create :create_vote

  attr_accessible :text, :title, :category_ids, :image

  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  has_one :vote, :dependent => :destroy
# -----------------------------------------------
  has_many :photos, :dependent => :destroy 
# -----------------------------------------------

  belongs_to :user

  validates :title, :presence => true, :length => { :minimum => 2 }
  validates :text, :presence => true, :length => { :minimum => 2 }
  
  scope :by_category_id, lambda {|cid| joins(:categories).where(['categories.id = ?',cid])}

  mount_uploader :image, ImageUploader
  


include PgSearch
pg_search_scope :search, against: [:title, :text],
	associated_against: {user: :name, comments: [:body]}

# end of 343 DB search in testing and production

	def self.text_search(query)
	  if query.present?
	    search(query)
	  else
	    scoped
	  end
	end

    protected
    
    def create_vote
      self.vote = Vote.create(:score => 0)
    end



end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  
  has_and_belongs_to_many :users
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :users
  belongs_to :country
end

app/models/user.rb
class User < ActiveRecord::Base

  before_create :create_role
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable ,:recoverable,
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :country_id, :state_id, :terms_of_service, :role_ids
  # attr_accessible :title, :body
  has_many :posts
  has_many :comments

  has_and_belongs_to_many :roles
  has_and_belongs_to_many :votes

  belongs_to :country
  belongs_to :state
  validates :name, :presence => true, :length => { :minimum => 2 }
  validates :email, :presence => true
  validates :terms_of_service, :acceptance => true


  private
    def create_role
      self.roles << Role.find_by_name(:user)  
    end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :score, :count_users
  has_and_belongs_to_many :users
  belongs_to :post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	load_and_authorize_resource

	before_filter :set_timezone 
	
	def set_timezone  
	 min = request.cookies['time_zone'].to_i
	 Time.zone = ActiveSupport::TimeZone[min]
	end 


	def index
		@posts = Post.order('created_at DESC').text_search(params[:query]).page(params[:page]).per(6)
		
		@posts = @posts.by_category_id(params[:cat]).page(params[:page]).per(6) if params[:cat].present?
	end
	def new
		
	end
	def create
  		
  		@post.user = current_user

  		if @post.save
  		  flash[:notice] = "Post created!"
  		  redirect_to post_path(@post.id)
  		else
  		  render 'new'
  		end
	end
	def show
		
	end
	def edit
		
	end
	def update
  		
  		if @post.update_attributes(params[:post])
  		  flash[:notice] = "Post updated"
  		  redirect_to post_path(@post.id)
  		else
  		  render 'edit'
  		end
	end
	def destroy
	  
	  @post.destroy
	  redirect_to posts_path
	end
	
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController

  load_and_authorize_resource

  def update
    @post = Post.find(params[:post_id])
    vote = @post.vote
       
    vote.score += 1 if params[:vote][:score] == "1"
    vote.score += 2 if params[:vote][:score] == "2"
    vote.score += 3 if params[:vote][:score] == "3"
    vote.score += 4 if params[:vote][:score] == "4"
    vote.score += 5 if params[:vote][:score] == "5"

    vote.count_users += 1

    vote.users << current_user
    
      respond_to do |format|
        if vote.save
          format.html { 
            redirect_to post_path(@post),
            :notice => "You vote counted!"
          }
          format.js
          # flash[:notice] = "You vote counted!"
          # redirect_to post_path(post)
        end
      end
  end
   

  def clear
    post = Post.find(params[:post_id])
    post.vote.update_attributes(:score => 0)
     
    flash[:notice] = "Clear!"
    redirect_to post_path(post)
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "You have already voted"
    redirect_to post_path(Post.find(params[:post_id]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
       	content_for(:title) { page_title  }
    end
      
    def avatar_url(i)
    	gravatar_id = Digest::MD5::hexdigest(i.email).downcase
    	"http://gravatar.com/avatar/#{gravatar_id}.png?s=58"
  	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/servants_helper.rb
module ServantsHelper
end

app/helpers/start_page_helper.rb
module StartPageHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> App | <%= content_for?(:title) ? yield(:title) : 'unknown' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"></a>
        <%= link_to ' Home', root_path, :class => 'brand' %>
        <div class="nav-collapse">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><%= link_to "Posts", posts_path %></li>
          <li class="divider-vertical"></li>
          <% if user_signed_in? %>
            <% if current_user.roles.first.name == "user" %>
              <li><%= link_to current_user.email, servant_path(current_user.id) %></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              <li class="divider-vertical"></li>
            <% elsif current_user.roles.first.name == "admin" %>
              <li><%= link_to current_user.name, '/', :class => 'admin_name' %></li>
              <li class = 'icon-exclamation-sign'></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Servants", servants_path, :class => 'admin_name' %></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Categories", categories_path, :class => 'admin_name' %></li>
              <li class="divider-vertical"></li>
            <% end %>  
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "sign in", new_user_session_path %></li>
            <li class="divider-vertical"></li>
              <%= form_for("user", :url => user_session_path, :html => {:class => 'navbar-form pull-left' } ) do |f| %>
                <%= f.text_field :email, :class => "input-small", :placeholder => "Email" %>
                <%= f.password_field :password, :class => "input-small", :placeholder => "Password"  %> 
                <%= f.submit 'Sign in', :class => "btn from_top_marg" %>
              <% end %>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
  </div>
    
      <div class="alert alert-success notic">
        <strong><%= flash[:notice] %></strong>
      </div>
      <div class="alert alert-error aler">
        <strong><%= flash[:alert] %></strong>
      </div>
    

<%= yield %>

</body>
</html>